## Recursion
<img src='DynProg_1.PNG',alt="Drawing" style="width: 500px;"/>

In [4]:
def hanoi(a='S',b='D',c='E',n=4):
    if n==0:
        return
    hanoi(a,c,b,n-1)
    print('move disc %d from %s to %s'%(n,a,b))
    hanoi(c,b,a,n-1)

In [6]:
hanoi(a='S',b='D',c='E',n=3)

move disc 1 from S to D
move disc 2 from S to E
move disc 1 from D to E
move disc 3 from S to D
move disc 1 from E to S
move disc 2 from E to D
move disc 1 from S to D


<img src='DynProg_2.PNG',alt="Drawing" style="width: 500px;"/>

In [28]:
# bubble sort with recursion
a=[2,5,6,9,0,1,3,7,4,8]

In [16]:
min(a)

0

In [32]:
a

[]

In [30]:
mod=[]
def bubble(x,mod):
    if len(mod)==10:
        return mod
    minimal = min(x)
    mod.append(minimal)
    x.remove(minimal)
    bubble(x,mod)
    return mod

In [31]:
bubble(a,mod)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
a=[2,5,6,9,0,1,3,7,4,8]

In [47]:
def bubble(x,n):
    if len(x[:n])==0:
        return x
    minimal = min(x[:n])
    x.remove(minimal)
    x.append(minimal)
    bubble(x,n-1)
    return x

In [48]:
a=[2,5,6,9,0,1,3,7,4,8]
bubble(a,n=len(a))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
len(mod)

0

<img src='DynProg_3.PNG',alt="Drawing" style="width: 500px;"/>

<img src='DynProg_4.PNG',alt="Drawing" style="width: 500px;"/>

<img src='DynProg_4.PNG',alt="Drawing" style="width: 500px;"/>

In [50]:
import numpy as np

In [55]:
a=np.array([[0,10,75,94],[-1,0,35,50],[-1,-1,0,80],[-1,-1,-1,0]])

In [56]:
a.shape

(4, 4)

In [59]:
a[0,0]

0

In [66]:
print(a)

[[ 0 10 75 94]
 [-1  0 35 50]
 [-1 -1  0 80]
 [-1 -1 -1  0]]


In [88]:
# count stations from zero
def min_cost(a, start, finish):
    if (start==finish or start==finish-1):
        return a[start,finish]
    temp = a[start,finish]
    for i in range(start+1,finish):
        minimal_cost = min_cost(a,start,i)+min_cost(a,i,finish)
        if temp > minimal_cost:
            temp = minimal_cost
    return temp

In [89]:
min_cost(a, 0, 3)

60

In [85]:
a[0,3]

94

In [90]:
a=np.array([[0,10,75,94],[-1,0,35,50],[-1,-1,0,5],[-1,-1,-1,0]])
print(a)

[[ 0 10 75 94]
 [-1  0 35 50]
 [-1 -1  0  5]
 [-1 -1 -1  0]]


In [91]:
# here should be three transfer and min = 10+35+5=50
min_cost(a, 0, 3)

50

<img src='DynProg_5.PNG',alt="Drawing" style="width: 600px;"/>

In [92]:
# count from zero. number of ways to go in the point with coord(x,y) on the square
def n_ways(x,y):
    if x==0 or y==0:
        return 1
    ways = n_ways(x-1,y) + n_ways(x,y-1)
    return ways

In [101]:
n_ways(2,2)

6

In [102]:
# check youself with square matrix. Number of ways from up left to bottom right
n=2 #with zero, so there is n+1 rows and columns
ways = np.math.factorial((n)*(n))/(np.math.factorial(n))**2
print('hand checked number of ways is %d'%(ways))

hand checked number of ways is 6


<img src='DynProg_6.PNG',alt="Drawing" style="width: 1000px;"/>

In [111]:
# Memorization with Fibonacci numbers
known = [1,1]
def fib(x):
    global known
    if x==1 or x==2:
        return 1
    if x<=len(known):
        return known[x-1]
    else:
        rez = fib(x-2)+fib(x-1)
        known.append(rez)
        return rez

In [118]:
fib(10)

55

In [121]:
np.array(known).flatten()

array([    1,     1,     2,     3,     5,     8,    13,    21,    34,
          55,    89,   144,   233,   377,   610,   987,  1597,  2584,
        4181,  6765, 10946, 17711, 28657, 46368, 75025])

<img src='DynProg_7.PNG',alt="Drawing" style="width: 1100px;"/>

In [148]:
a=[9,4,3,0,7,2,3] # 4307 -- 4 digits
longest=0
def numb(a):
    global longest
    if len(a)<2:
        return 0
    if len(a)%2==0:
        if sum(a[:int(len(a)/2)])==sum(a[int(len(a)/2):]):
            longest = max(longest, len(a))
            return longest
    l1=numb(a[1:])
    l2=numb(a[:-1])
    #print(l1)
    longest=max(l1,l2)
    return longest


In [149]:
numb(a)

4

In [155]:
longest=0
b=[1,4,7,8,4,7,8,0,9,9] # [...7,8,4,7,8,0,9,9] -- 8 digits
numb(b)

8